= WildFly Documentation
:toc: left
:wildfly-latest-major: 39

++++
<link rel="stylesheet" href="search/search.css">
++++

This documentation is organized into four main sections:

* _Getting Started with WildFly_ provides core application server information, releases, and APIs.
* _Build Applications with WildFly_ covers using Maven and related development tools.
* _Build & Deploy WildFly on the Cloud_ includes guides for containerization and orchestration.
* _Provision WildFly & Build Feature Packs_ explains advanced provisioning and server customization.

== Getting Started with WildFly

WildFly is a powerful, modular, and lightweight application server that helps you build amazing enterprise Java applications.

To learn more about WildFly {wildfly-latest-major}, visit:

=== Official WildFly Documentation

The official WildFly {wildfly-latest-major} documentation provides comprehensive guides on installation, administration, development, and more.

Learn more about the official link:{wildfly-latest-major}[WildFly {wildfly-latest-major}] Documentation.

=== Guides

The WildFly Guides offer practical, hands-on tutorials covering various aspects of WildFly, including automation, containerization, messaging, MicroProfile, and more.

Learn more about the WildFly link:https://www.wildfly.org/guides/[Guides].

=== Quickstarts

Quickstarts are ready-to-run example projects demonstrating key features of WildFly. They serve as excellent starting points for understanding and implementing specific functionalities of the application server.

Learn more about the WildFly link:https://docs.wildfly.org/{wildfly-latest-major}/Quickstarts.html[Quickstarts].

=== Jakarta EE 10 Platform API

The Jakarta EE 10 Platform API defines the standard for building enterprise applications in Java. It includes specifications for various components like Jakarta Contexts and Dependency Injection, Jakarta RESTful Web Services, and more.

Learn more about the link:https://jakarta.ee/specifications/platform/10/apidocs/[Jakarta EE 10 Platform] API.

=== MicroProfile 7.1 API

MicroProfile 7.1 provides a set of APIs designed to optimize Java EE for microservices architectures. It includes specifications for features like configuration, fault tolerance, metrics, and more.

Learn more about the link:https://javadoc.io/doc/org.eclipse.microprofile/microprofile/7.1/index.html[MicroProfile 7.1] API.

=== Previous Releases

For information on previous WildFly releases, including documentation and guides, visit the link:./archives[WildFly Archives].

== Build Applications with WildFly

=== WildFly Maven Plugin

The WildFly Maven plugin allows you to manipulate a WildFly server directly from a Java Maven project.
Its features include:

* Deploy, redeploy or undeploy your application
* Add resources
* Execute CLI commands
* Run a standalone server within Maven
* Provision & package a WildFly server fit for your application
* Build a container image with WildFly and your application
* Build a Bootable Jar application

Learn more about the link:wildfly-maven-plugin[WildFly Maven Plugin].

=== WildFly Glow

WildFly Glow is a tool to automatically discover an application's requirements and provision WildFly with the right set of capabilities.
WildFly Glow is integrated in the WildFly Maven Plugin to streamline application development and deployment. It can also be used with Arquillian for integration testing.

Learn more about link:wildfly-glow[WildFly Glow].

=== Bootable JAR

[NOTE]
The WildFly Maven Plugin now incorporates the ability to produce Bootable JAR applications and is the recommended way to do it.

Bootable JAR is a Maven plugin to build bootable JAR applications.

Learn more about link:bootablejar[Bootable Jar].

[[wildfly-on-kubernetes]]
== Build & Deploy WildFly on the Cloud

There are different tools to build and deploy WildFly on the Cloud.

=== WildFly Container

Our original container image that provides a standalone WildFly server.
Use this image to add your deployments and build your application image.

Learn more about link:wildfly-container[WildFly Container].

=== Helm Chart

Build & Deploy your Java applications with WildFly on Kubernetes and OpenShift with a Helm Chart.

Learn more about the link:wildfly-charts[Helm Chart for WildFly].

=== Operator for Kubernetes & OpenShift

The WildFly Operator simplifies deployment and maintenance of stateful containerized applications
for Kubernetes and OpenShift.

Learn more about the link:wildfly-operator[WildFly Operator].

=== Source-to-Image (S2I) Builder & Runtime Images

Use the Source-to-Image (S2I) Builder image to build a container image on OpenShift directly from your Git repository.
Use the Runtime image to trim the container so it contains the minimal dependencies required to run WildFly.

Learn more about the link:wildfly-s2i[S2I Builder & Runtime Images].

== Provision WildFly & Build Feature Packs

=== Galleon

Galleon is a Provisioning tool to create and maintain software distributions such as WildFly.
It also provides a Maven plugin to build feature-packs for WildFly & provision WildFly-based distributions

Learn more about link:galleon[Galleon] and its link:galleon-plugins[Plug-ins documentation].

=== Prospero

Prospero is a high-level tool designed to install and manage updates of WildFly servers.
Its features include:

* Provision WildFly servers
* Update or revert updates to WildFly servers
* Track updates history

Learn more about link:prospero[Prospero].

++++
<!-- Search Dialog -->
<div id="searchDialog" class="search-dialog">
    <div class="dialog-content">
        <div class="dialog-header">
            <div class="dialog-header-top">
                <h3 class="dialog-title">Search Documentation</h3>
                <button class="close-button" id="closeDialog">&times;</button>
            </div>
            <div class="dialog-search-container">
                <input type="text" id="dialogSearchInput" class="dialog-search-input" placeholder="Search docs..." autocomplete="off">
                <button type="button" id="dialogSearchButton" class="dialog-search-button">Search</button>
            </div>
        </div>
        <div class="dialog-body">
            <div id="searchResults">
                <div class="loading">Enter a search term to begin...</div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/FlexSearch/0.8.2/flexsearch.bundle.min.js"></script>
<script src="search/search.js"></script>
++++