= WildFly Design Documentation
:ext-relative: {outfilesuffix}
ifdef::env-github[:imagesdir: images/]
:toc!:

This section of the WildFly documentation is meant to record various documents written to explain various aspects of the WildFly server and the various tooling and release deliverables associated with it.

The documents herein are primarily intended for use by developers of WildFly or by advanced users of WildFly who seek a deeper understanding of how WildFly works. They are not meant to serve as general user documentation, and any content primarily meant for end users should be located elsewhere.

These documents are not expected to be maintained after the time they are first merged into https://github.com/wildfly/wildfly.github.io. The authors of some documents may choose to update them over time, but readers should not assume accuracy of any content beyond the date it was initially merged.

If authors do maintain documents over time, beyond correction of errors in the initial document, they should maintain a changelog in the document itself noting the history.

Documents are to be located in the same directory as this document, and each document must be linked from at least one 'toc-<topic_name>.adoc' file located in this folder. The 'toc-<topic_name>.adoc' files are simple link collections to specific content relevant to a particular topic. Topic-specific subdirectories are discouraged as they may lead to broken links in the future. Images should be located in the 'images' subdirectory.

== Design Document Topics

* link:toc-core-architecture{outfilesuffix}[Core Architecture and the Server Kernel]